apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard-rwo
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistenDisk:
    pdName: kaizen
    fsType: ext4